# Generated by Django 2.1.dev20171009161908 on 2017-10-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200)),
                ('squaremeter', models.IntegerField(default=40)),
                ('price', models.IntegerField(default=10000)),
                ('type', models.CharField(max_length=50)),
                ('wall', models.CharField(max_length=50)),
                ('heating', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('rooms', models.IntegerField(default=3)),
                ('parking', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2017)),
                ('furnitured', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('view', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=5000)),
                ('valid', models.BooleanField(default=True)),
                ('unread', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=40)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
    ]
