# Generated by Django 2.1.dev20171009161908 on 2017-10-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='adds',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
    ]
