# Generated by Django 2.1.dev20171009161908 on 2017-10-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171023_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='adds',
            name='description',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adds',
            name='furnitured',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adds',
            name='lift',
            field=models.CharField(max_length=10),
        ),
    ]
